In [1]:
import math

In [7]:
a=int(input("enter the 1 no:"))
b=int(input("enter the 2 no.:"))
sum=a + b
print(sum)

enter the 1 no:7
enter the 2 no.:8
15


In [8]:
2**4

16

In [9]:
4**2

16

In [10]:
10**2

100

In [12]:
a=int(input("enter the no.:"))
print(a**2)

enter the no.:5
25


In [18]:
for i in range (1,10):
    print(i,end='')

123456789

In [24]:
string="python"
for i in string:
    print(i)

p
y
t
h
o
n


In [29]:
a=5
b=6


In [31]:
if a>b:
    print("a is greater")
    
else:
    print("b is greater")

b is greater


In [32]:
type(a)

int

In [33]:
type(string)

str

In [36]:
import pandas as pd
data = [["Name", "Age", "City"], ["Alice", 25, "New York"], ["Bob", 30, "Los Angeles"]]
df = pd.DataFrame(data)
print(df)

       0    1            2
0   Name  Age         City
1  Alice   25     New York
2    Bob   30  Los Angeles


In [1]:
import numpy as np

In [39]:
arr = np.zeros(5)

# Create a NumPy array with ones
arr = np.ones(5)

# Create an array with a range of numbers
arr = np.arange(2, 10)  # Start at 2, end before 10

# Print the arrays
print(arr)

[2 3 4 5 6 7 8 9]


In [3]:
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [2]:
arr=np.ones(6)
print (arr)
type(arr)

[1. 1. 1. 1. 1. 1.]


numpy.ndarray

In [45]:
arr2=np.arange(2,20)
print(arr2)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [51]:
arr3=[3,2,4,22,1,1,5,6,87,5,44,3]
    

In [52]:
type (arr3)

list

In [53]:
len(arr2)

18

In [54]:
len(arr3)

12

In [55]:
 pow(7,2)

49